# PanDA site common configuration for all Data Facilities
# --compute-site is necessary to use this yaml for bps submit

includeConfigs:
- ${CTRL_BPS_PANDA_DIR}/config/bps_panda.yaml

project: dev
campaign: quick
s3EndpointUrl: "https://storage.googleapis.com"
payloadFolder: payload
fileDistributionEndPoint: "file://${LSST_RUN_TEMP_SPACE}/panda_cache_box/{payloadFolder}/{uniqProcName}/"

# Job environment setup
custom_lsst_setup: ""
setupLSSTEnv: >
  unset PYTHONPATH;
  source /cvmfs/sw.lsst.eu/almalinux-x86_64/lsst_distrib/{LSST_VERSION}/loadLSST.bash;
  setup lsst_distrib;
  {custom_lsst_setup}

# Other job variables
jobInitDir: "`pwd`"
jobLogDir: "{jobInitDir}"
jobContainer: >
  /bin/bash -c "{payloadCommand}" >&2;
jobCleanup: "rm -fr EXEC_REPO-*;"

# Specify memory request, queue for finalJob
finalJob:
  queue: "Rubin_Merge"
